import Head from "next/head";
import MainHero from "../components/MainHero";
import OtherPostsSection from "../components/OtherPostsSection";
import TrendingSection from "../components/TrendingSection";
import { getAllPostsForHome } from "../helpers/getPosts";

export default function Home({ data }) {
  // const heroPostsId = [2870, 2436, 1324, 1948, 2162];

  const heroPosts = [];
  const otherHomePagePosts = [];
  const filterPosts = () => {
    for (let item = 0; item < data.length; item++) {
      if (
        data[item].node.postId === 2870 ||
        data[item].node.postId === 2436 ||
        data[item].node.postId === 1324 ||
        data[item].node.postId === 1948 ||
        data[item].node.postId === 2162
      ) {
        heroPosts.push(data[item]);
      } else {
        otherHomePagePosts.push(data[item]);
      }
    }
  };
  filterPosts();

  // console.log(otherHomePagePosts);

  return (
    <main className="mx-auto max-w-6xl px-3">
      {/* {console.log(data)} */}
      {/* <NextSeo
        title="Chi_Dev Portfolio"
        description="This is My portfolio shocasing my projects"
        canonical="https://www.canonical.ie/"
        openGraph={{
          url: "https://www.url.ie/a",
          title: "Chi_Dev Portfolio",
          description: "Open Graph Description",
          images: [
            {
              url: screenshot,
              width: 800,
              height: 600,
              alt: "Og Image Alt",
              type: "image/jpeg",
            },
            ,
            { url: screenshot },
          ],
          site_name: "SiteName",
        }}
        twitter={{
          handle: "@ChibuikeNnaji10",
          site: "@ChibuikeNnaji10",
          cardType: "summary_large_image",
        }}
      /> */}
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHero heroPosts={heroPosts} />
      <TrendingSection trendingPosts={otherHomePagePosts.slice(0, 6)} />
      <OtherPostsSection
        otherPosts={otherHomePagePosts.slice(6, otherHomePagePosts.length - 1)}
      />
    </main>
  );
}

export async function getStaticProps() {
  const res = await getAllPostsForHome();

  return {
    props: {
      data: res,
    },
  };
}
